### ISSUE TITLE
Files are overwritten because of re-used index. 

### ISSUE THREAD

**Issue by TheSkyentist** [tiaraandmr/spec-uao#1]
For loop is initialized with index i:
https://github.com/tiaraandmr/spec-uao/blob/ddd0852724d07ebccf641f910efdebf5796feeef/smooth_spec.py#L32

Variable is re-used in inner loop, leading to unpredictable behavior:
https://github.com/tiaraandmr/spec-uao/blob/ddd0852724d07ebccf641f910efdebf5796feeef/smooth_spec.py#L54

**Comment by tiaraandmr** [comment]
Fix the re-used index.
https://github.com/tiaraandmr/spec-uao/blob/f3be764c102d04c5acf90ce1af7af92e071aeda7/smooth_spec.py#L54C5-L60C107

**Comment by tiaraandmr** [comment]
Fix the re-used index.
https://github.com/tiaraandmr/spec-uao/blob/f3be764c102d04c5acf90ce1af7af92e071aeda7/smooth_spec.py#L54C5-L60C107
